### ISSUE TITLE
Update server

### ISSUE THREAD

**Issue by n3t** [Percha/fieldsattach_j3#50]
Hello, 

current installation of Fieldsattach is pointing http://www.percha.com/update/fieldsattach-update_j3.xml as its update server. However informations stored there are bit old, It is showing last version 3.4.8.8

Would be great to have this updated, to enable "in joomla" updates.

Pavel

**Comment by n3t** [comment]
Hi, 

currently http://www.percha.com/update/fieldsattach-update_j3.xml gives 404 error, any progress with this?

Pavel

**Comment by graredcr** [comment]
Done

Cristian

**Comment by n3t** [comment]
Hi, 

http://www.percha.com/update/fieldsattach-update_j3.xml already works, however it is still showing 3.4.8.8 as latest version.

Pavel

**Comment by graredcr** [comment]
Ok, done

**Comment by n3t** [comment]
Tested, works.

Thank you
